apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: set-card-game-server
        app.kubernetes.io/component: set-card-game-server
        app.kubernetes.io/instance: set-card-game-server
      name: set-card-game-server
    spec:
      ports:0
        - name: 8080-tcp
          port: 8080
          protocol: TCP
          targetPort: 8080
      selector:
        deployment: set-card-game-server
      sessionAffinity: None
      type: ClusterIP
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        app: set-card-game-server
        app.kubernetes.io/component: set-card-game-server
        app.kubernetes.io/instance: set-card-game-server
      name: set-card-game-server
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: set-card-game-server
      template:
        metadata:
          labels:
            app: set-card-game-server
          name: set-card-game-server
        spec:
          containers:
            - image: sranker/set-card-game-server:latest
              imagePullPolicy: IfNotPresent
              name: set-card-game-server
              ports:
                - containerPort: 8080
                  protocol: TCP
          restartPolicy: Always
