apiVersion: v1
kind: List
items:
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    labels:
      app.kubernetes.io/name: set-card-game-server
    name: set-card-game-server
  spec:
    output:
      to:
        kind: DockerImage
        name: docker.io/sranker/set-card-game-server:latest
    source:
      # Expect a local directory to be streamed to OpenShift as a build source
      type: Binary
      binary: {}
    strategy:
      type: Docker
      dockerStrategy:
        # Find the image build instructions in ./Dockerfile
        dockerfilePath: Dockerfile
