#SECRETS
spring.config.import=optional:secrets.properties

#DATABASE
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

#REDIS
spring.data.redis.host=${SPRING_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_REDIS_PORT:6379}
spring.data.redis.timeout=2000ms
spring.data.redis.lettuce.pool.max-active=8
spring.data.redis.lettuce.pool.max-idle=8
spring.data.redis.lettuce.pool.min-idle=0

#SWAGGER
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger.html

#LOGIGNG
logging.level.root=INFO

#SECURITY
security.jwt.secret-key=${JWT_SECRET}
security.jwt.expiration-time=${JWT_EXPIRATION_TIME}

# Super Admin Credentials
super.admin.username=${SUPER_ADMIN_USERNAME}
super.admin.password=${SUPER_ADMIN_PASSWORD}